Problem 2

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


var fibo = [];
var j = 0;
var sum = 0;

for(i = 1; i <= 4000000;) {
  fibo.push(i);
  if (j - 1 < 0) {
    i += 1;
    j += 1;
  }
  else {
    i = i + fibo[j - 1];
    j += 1;
  }
}

for(k = 0; k < fibo.length; k++) {
  if(fibo[k]%2 === 0) {
    sum += fibo[k];
  }
}

console.log(sum);
